version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  # python: circleci/python@0.2.1

jobs:
  build-and-test:
    # executor: python/default
    executor: aws-cli/default
    steps:
      - checkout

      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      - run:
          command: eb deploy
      #     command: ./manage.py test
      #     name: Test

workflows:
  main:
    jobs:
      - build-and-test
