version: 2.1

jobs:
  release:
    working_directory: ~/app
    # executor: python/default
    docker:
      - image: circleci/python@0.2.1
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get install python-pip python-dev build-essential
            pip install --upgrade setuptools
            pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy

workflows:
  main:
    jobs:
      - release
        # filters:
        #   branches:
        #     only:
        #       - staging
        #       - master
