# Generated by Django 3.0.3 on 2020-06-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0003_auto_20200617_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devPortfolio.TechTag'),
        ),
        migrations.AlterField(
            model_name='techtag',
            name='tech',
            field=models.CharField(max_length=100),
        ),
    ]
