# Generated by Django 3.0.3 on 2020-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0004_auto_20200617_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='devPortfolio.TechTag'),
        ),
    ]
