# Generated by Django 3.0.3 on 2020-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0005_auto_20200617_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='devPortfolio.TechTag'),
        ),
    ]
