# Generated by Django 3.0.3 on 2020-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0008_auto_20200618_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, upload_to='files/resume'),
        ),
    ]
