# Generated by Django 3.0.3 on 2020-08-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0009_about_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, upload_to='files/certs')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='certs',
            field=models.ManyToManyField(blank=True, to='devPortfolio.CertDoc'),
        ),
    ]
