# Generated by Django 3.0.3 on 2020-02-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hiking',
            new_name='HikingKey',
        ),
    ]
