# Generated by Django 3.0.3 on 2020-06-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0002_techtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devPortfolio.TechTag'),
        ),
        migrations.AddField(
            model_name='techtag',
            name='icon',
            field=models.ImageField(null=True, upload_to='pictures/tech'),
        ),
    ]
