# Generated by Django 3.0.3 on 2020-06-18 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devPortfolio', '0007_auto_20200618_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devPortfolio.TechKeywords'),
        ),
    ]
